[package]
name = "game_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0.4"
bevy = { version = "0.15.3" }

[dev-dependencies]
trybuild = "1.0"